### ISSUE TITLE
Call to a member function delete() on int

### ISSUE THREAD

**Issue by CS76** [maize-tech/laravel-markable#21]
Deleting a markable model throws the `Call to a member function delete() on int` error. Looks like the `$markableModel->likes()` is not returning the relationship. 

"php": "^7.3|^8.1"
"laravel/framework": "^9.22.1"
"maize-tech/laravel-markable": "^1.0"

**Comment by ianclemence** [comment]
Hello,

I am encountering the same issue now when I try to delete a user after creating a custom mark model 'Followers'. 

"php": "^8.2",
"maize-tech/laravel-markable": "^2.2",
"laravel/framework": "^11.9",
