### ISSUE TITLE
Accept Laravel 11.x

### ISSUE THREAD

**Issue by danielveselinov** [maize-tech/laravel-markable#68]
Well, since the package doesn't support Laravel 11.x we can't upgrade our projects, please if you could add it to the package, and/or merge the existing PRs that are already done for this matter..

**Comment by danielveselinov** [comment]
@enricodelazzari  @riccardodallavia

**Comment by enricodelazzari** [comment]
just merged!

**Comment by enricodelazzari** [comment]
just merged!

**Comment by agelospanagiotakis** [comment]
does this actualy work in laravel 11 ?
it has been tested ?
